FROM debian:stable-slim

RUN apt update
RUN apt install -y python3-pip nano curl wget openssh-server git

ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 ~/.ssh/id_rsa
RUN chmod 600 ~/.ssh/id_rsa.pub

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt

CMD [ "bin/bash" ]