FROM debian:bullseye-slim

WORKDIR /generate_timesheet

RUN apt-get update
RUN apt-get install -y python3-pip

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN rm requirements.txt

CMD [ "/bin/bash" ]