FROM debian:stable-slim

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y curl git nano python3 python3-pip

ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN rm requirements.txt

CMD [ "/bin/bash" ]